CREATE OR REPLACE CORTEX SEARCH SERVICE "MED_DEMO"."CLINICAL"."CLINICAL_NOTES_CSS" ON NOTE_TEXT ATTRIBUTES NOTE_ID,PATIENT_ID WAREHOUSE = "MED_WH" TARGET_LAG = '5 minutes' AS (
  SELECT NOTE_TEXT, NOTE_ID, PATIENT_ID
  FROM MED_DEMO.CLINICAL.NOTES
);